[package]
name = "backlink1dpod/stonebl1d"
version = "0.1.0"
description = "My Hugo Blog on Wasmer"
entrypoint = "start"  # <--- Quan trá»ng: BÃ¡o cho Wasmer biáº¿t lá»‡nh nÃ o lÃ  lá»‡nh cháº¡y chÃ­nh

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "public"

[[command]]
name = "start"
# ðŸ‘‡ Sá»¬A QUAN TRá»ŒNG: "webserver" viáº¿t liá»n, KHÃ”NG cÃ³ dáº¥u gáº¡ch ngang (-)
module = "wasmer/static-web-server:webserver"
# ðŸ‘‡ Quay vá» runner chuáº©n "wasi" (nhanh vÃ  á»•n Ä‘á»‹nh hÆ¡n URL https...)
runner = "wasi"
annotations = { "wasi.env" = ["SERVER_ROOT=/public", "PORT=80"] }