name: Deploy to BunnyCDN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # CÃ i Ä‘áº·t Hugo
      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.151.0/hugo_extended_0.151.0_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      # CÃ i Ä‘áº·t Node/NPM (Ä‘á»ƒ cÃ i theme)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Build web
      # QUAN TRá»ŒNG: Pháº£i set baseURL Ä‘Ãºng link Pull Zone cá»§a Bunny
      - name: Build Hugo
        run: hugo --minify --baseURL "https://bl1d.b-cdn.net/"

      # Upload lÃªn BunnyCDN Storage
      - name: Upload to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.5
        with:
          source: "public"
          destination: "/"
          storageZoneName: "${{ secrets.BUNNY_STORAGE_NAME }}"
          storagePassword: "${{ secrets.BUNNY_API_KEY }}"
          accessKey: "${{ secrets.BUNNY_API_KEY }}"
          
          # ğŸ‘‡ THÃŠM DÃ’NG NÃ€Y Äá»‚ CHá»ŒN SERVER SINGAPORE
          storageEndpoint: "sg.storage.bunnycdn.com"
          
          upload: true
          remove: true